name: zyte-deployment
run-name: Deploy to Zyte

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install shub
        run: |
          pip install shub -U --quiet --no-cache-dir

      - name: Configure API KEY
        run: |
          echo "${{ secrets.ZYTE_API_KEY }}" | shub login

      - name: Deploy to Zyte
        run: |
          shub deploy
